name: Load Test

on:
  push:
    branches:
      - main

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install K6
      run: sudo apt-get update && sudo apt-get install -y k6

    - name: Run K6 load test
      run: k6 run loadtest.js
